InternalServerError exception added
laget-se/laget.Exceptions pull request #6
Opened 2021-09-21 13:34 UTC by morganlun

Nytt exception som hanterar InternalServerError.

Se så att testerna fungerar för det nya exception

2021-09-21 13:40 UTC, gonace requested changes

2021-09-21 13:40 UTC, gonace commented on laget.Exceptions/InternalServerErrorException.cs
> +    public class InternalServerErrorException : Exception
Jag skulle föredra `UnhandledException` eftersom det mer beskriver vad som har hänt, `Internal Server Error` är ju bara resultatet av ett ohanterat fel.

2021-09-21 13:48 UTC, gonace approved these changes
I approve this :+1: with a 🍌

2021-09-22 06:43 UTC, k3V1nlund63R9 approved these changes

2021-09-22 06:45 UTC, merged